Added delete url functionality
shashwatj07/url-shortener pull request #15
Opened 2022-01-17 04:12 UTC by Dhruv88

Resolves #14  
Resolves #16

2022-01-18 03:58 UTC, shashwatj07 requested changes
update readme

2022-01-25 02:57 UTC, shashwatj07 requested changes

2022-01-25 02:57 UTC, shashwatj07 commented on constants.go
> +const DEFAULT_EXPIRY_DATE = 30
please make it ```DEFAULT_VALIDITY_DAYS```

2022-01-25 02:57 UTC, shashwatj07 commented on handlers.go
> +
remove blank line

2022-01-25 02:57 UTC, shashwatj07 commented
"expiry date" should be modified to "validity" everywhere

2022-01-25 05:09 UTC, Dhruv88 commented on constants.go
> +const DEFAULT_EXPIRY_DATE = 30
Done

2022-01-25 05:09 UTC, Dhruv88 commented on handlers.go
> +
Done

2022-01-25 05:13 UTC, Dhruv88 commented
> "expiry date" should be modified to "validity" everywhere

I have done this in most places except a few which are
line 6 in entity.go and lines 45-47 in repository.go where it is actually the UNIX timestamp of the expiry date and not just a validity period.

2022-01-25 08:33 UTC, shashwatj07 approved these changes

2022-01-25 08:33 UTC, merged