Added Analytics feature
shashwatj07/url-shortener pull request #18
Opened 2022-01-24 11:28 UTC by Dhruv88

Solves #17 
Keeps track of per day visits to URL from the day of creation to expiry.
Also an API to retrieve this count for a particular URL has been added.

2022-01-25 17:18 UTC, shashwatj07 commented
resolve conflicts

2022-01-26 08:33 UTC, Dhruv88 commented
> resolve conflicts

Done

2022-02-09 10:13 UTC, shashwatj07 commented
We should have a way of handling cases where the URL has never been used.

2022-02-09 10:14 UTC, shashwatj07 requested changes
make this change

2022-02-09 10:14 UTC, shashwatj07 commented on README.md
> +```
```
curl http://localhost:8080/analytics/<random-hash|custom-alias> -H "Authorization: Bearer <auth_token>"
```

2022-02-09 10:29 UTC, shashwatj07 approved these changes

2022-02-09 10:29 UTC, merged